name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: apt install libgtk-4-dev libgee-0.8-dev meson ninja-build
      - name: Build website
        run: meson build
      - name: Build with Ninja
        run: ninja
        working-directory: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/libhelium-1
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com